#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Jekyll Boilerplate MI

# Short bio or description (displayed in the header)
description: Boilerplate f√ºr Jekyll Modulwebsites

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/th-koeln/mi-communicate/master/assets/images/box.png

# Where are we?
timezone: Europe/Berlin

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://th-koeln.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/mi-jekyll-boilerplate"


permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# be sure that you use kramdown as markdown processor
markdown: kramdown

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  extensions: [footnotes]
  footnote_location: 'my_footnotes'
  parse_block_html: true
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed
  sass_dir: mi-lib/_sass

# Zur Abtrannung der Aufgabe
excerpt_separator: "<!--aufgabe-->"

# Use the following plug-ins
plugins_dir:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'CNAME', '_tools/']

  # Hier bitte Navigationsitems eintragen
navigation:
  - url: timetable/
    name: Zeitplan
    
  - url: angebote/
    name: Angebote

  - url: links/
    name: Links

  - url: faq/
    name: FAQ

  - url: niveaustufen/
    name: Bewertung

collections:
  lehrveranstaltungen:
    output: true
  faq:
    output: false
  snippets:
    output: false
  links:
    output: false
  news:
    output: false

defaults:
  -
    scope:
      path: ""
      type: lehrveranstaltungen
    values:
      layout: lehrveranstaltung
  -
    scope:
      path: ""
      type: faq
    values:
      layout: faq